Feature startup
bizip/math_magicians pull request #2
Opened 2022-05-31 20:28 UTC by bizip

**What does this PR do?**

- Add UI for calculator

**Description of Task to be completed**

All tasks related to deployment are completed 

**How should this be manually tested?**

1. Clone this repository and switch to `feature-startup`
2. Install all required dependencies `npm install`
3. Run `npm start`

2022-05-31 21:10 UTC, Wes-Isaac requested changes
Hi @bizip, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linters are set up properly ✔️.
- Great summary😲. 
- Project works as expected 😮

## Required Changes ♻️

- [ ] Kindly remove unused files generated while creating the react app as it's a requirement.
![image](https://user-images.githubusercontent.com/59416136/171284927-0c1bc42c-23e2-4c30-a657-cfd89580af0f.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-31 21:10 UTC, Wes-Isaac commented on src/App.js
>      </div>
- [ ] Great job so far, to be consistent it's better to use a class-based component, kindly fix that.

2022-05-31 21:10 UTC, Wes-Isaac commented on src/components/Calculator.module.css
> +}
- [ ] [_OPTIONAL_] It would be better to access the calculator without scrolling so that it's easy to use.

2022-06-01 08:42 UTC, KDlamini approved these changes
### Hi @bizip 🙋‍♀️,  

Great job! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

# Status: Approved ✔️ 

![simon](https://user-images.githubusercontent.com/38088818/171364198-b81690dd-ac15-468a-a63a-b1c089c9003c.gif)

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 06:55 UTC, merged